import IOffer, { OfferCategoryType } from "@/types/Offer";

const offers: IOffer[] = [
  {
    category: "Team",
    date: "14 FEB 2022",
    daysCount: 3,
    nightsCount: 3,
    price: 700,
    title: "Loga Sea",
    type: "Relax",
    imageUrl: "/images/offers/loga-sea.png",
  },
  {
    category: "Team",
    date: "14 FEB 2022",
    daysCount: 3,
    nightsCount: 3,
    price: 700,
    title: "Alanya",
    type: "Relax",
    imageUrl: "/images/offers/loga-sea.png",
  },
  {
    category: "Team",
    date: "14 FEB 2022",
    daysCount: 3,
    nightsCount: 3,
    price: 700,
    title: "Hurghada",
    type: "Relax",
    imageUrl: "/images/offers/loga-sea.png",
  },
  {
    category: "Couple",
    date: "18 JUN 2022",
    daysCount: 4,
    nightsCount: 3,
    price: 400,
    title: "Ansgar Scheffold",
    type: "Adventure",
    imageUrl: "/images/offers/ansgar-scheffold.png",
  },
  {
    category: "Couple",
    date: "18 JUN 2022",
    daysCount: 4,
    nightsCount: 3,
    price: 400,
    title: "Venice",
    type: "Adventure",
    imageUrl: "/images/offers/ansgar-scheffold.png",
  },
  {
    category: "Couple",
    date: "18 JUN 2022",
    daysCount: 4,
    nightsCount: 3,
    price: 400,
    title: "Dominican Republic",
    type: "Adventure",
    imageUrl: "/images/offers/ansgar-scheffold.png",
  },
  {
    category: "Family",
    date: "22 DEC 2022",
    daysCount: 7,
    nightsCount: 6,
    price: 340,
    title: "Lona X",
    type: "Relax",
    imageUrl: "/images/offers/lona-x.png",
  },
  {
    category: "Family",
    date: "22 DEC 2022",
    daysCount: 7,
    nightsCount: 6,
    price: 340,
    title: "Bangkok",
    type: "Relax",
    imageUrl: "/images/offers/lona-x.png",
  },
  {
    category: "Family",
    date: "22 DEC 2022",
    daysCount: 7,
    nightsCount: 6,
    price: 340,
    title: "Costa Dorada",
    type: "Relax",
    imageUrl: "/images/offers/lona-x.png",
  },
];

export const offerCategories: OfferCategoryType[] = [
  "Team",
  "Couple",
  "Family",
];

export default offers;
